version: '3.8'
services:
  db:
    image: postgres:14.2-alpine
    user: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./db/data:/var/lib/postgresql/data
    networks:
      - "database_network"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    ports:
      - '3000:3000'
    restart: always
    volumes:
      - ./server:/usr/local/go/src/gin_api
    networks:
      - "database_network"
volumes:
  db:
    driver: local
networks:
  database_network:
    name: "database_network"
