FROM golang:1.18

WORKDIR /usr/local/go/src/gin_api

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .
RUN go install gin_api

CMD ["gin_api"]
